linter:
  rules:
    - always_declare_return_types
    - avoid_empty_else
    # - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - avoid_void_async
    - await_only_futures
    - avoid_implementing_value_types
    - avoid_null_checks_in_equality_operators
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null_for_void
    - avoid_types_as_parameter_names
    - avoid_relative_lib_imports
    - avoid_unused_constructor_parameters
    - camel_case_types
    - cancel_subscriptions
    - cascade_invocations
    - comment_references
    #- constant_identifier_names
    - control_flow_in_finally
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - hash_and_equals
    - prefer_void_to_null
    - avoid_print
    - avoid_returning_null_for_future
    - always_put_required_named_parameters_first
    - avoid_bool_literals_in_conditional_expressions
    - prefer_if_null_operators
    - constant_identifier_names
    - file_names
    - unnecessary_this
    - omit_local_variable_types
    - prefer_single_quotes
    - always_require_non_null_named_parameters
    - avoid_single_cascade_in_expression_statements
    - camel_case_extensions
    - curly_braces_in_flow_control_structures
    - library_names
    - no_duplicate_case_values
    - null_closures
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_final_fields